name: '${project.name}'
version: '${project.version}'
main: app.vercel.minecraftcustoms.mccenchants.Main
api-version: 1.18
authors: [ Nedarass ]
description: '${project.description}'
website: https://minecraftcustoms.vercel.app

commands:
  mccenchants:
    description: 'command'
    aliases: [mcc]
